modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/FTBTeam/FTB-Mods-Issues/issues"
license = "All Rights Reserved"

[[mods]]
modId = "ftbquests"
version = "${version}"
displayName = "FTB Quests"
authors = "FTB Team"
description = '''
Lets you easily create and play with quests
'''

[[dependencies.ftbquests]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.20)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbquests]]
modId = "architectury"
mandatory = true
versionRange = "[6.3.49,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbquests]]
modId = "ftblibrary"
mandatory = true
versionRange = "[1902.4.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.ftbquests]]
modId = "ftbteams"
mandatory = true
versionRange = "[1902.2.9-build.61,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.ftbquests]]
modId = "itemfilters"
mandatory = true
versionRange = "[1902.2.9-build.46,)"
ordering = "AFTER"
side = "BOTH"
